import os
import sqlite3
import hmac
import json
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
import uvicorn

BASE_DIR = Path(__file__).resolve().parent
DB_PATH = Path(os.environ.get("DB_PATH", BASE_DIR / "wow_vote.db"))
HTML_PATH = BASE_DIR / "index.html"
HISTORY_PATH = BASE_DIR / "history.html"
# The electoral map SVG is generated by tools/generate_map.py and inlined into
# index.html at this placeholder, so CSS and click handlers can reach its zones.
MAP_PATH = BASE_DIR / "partials" / "azeroth-map.svg"
MAP_PLACEHOLDER = "<!-- azeroth-map.svg -->"
STATIC_DIR = BASE_DIR / "static"
STATIC_DIR.mkdir(exist_ok=True)

app = FastAPI(title="WoW Forever Faction Vote Simulator")
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")
sync_lock = threading.Lock()

DEFAULT_PLAYERS = [
    # Horde (20)
    {"id": 1, "name": "rkkixlol", "faction": "Horde", "c": True, "s": False, "r": False, "is_sodam": False},
    {"id": 2, "name": "drey", "faction": "Horde", "c": True, "s": True, "r": True, "is_sodam": False},
    {"id": 3, "name": "korovaemae", "faction": "Horde", "c": False, "s": False, "r": False, "is_sodam": False},
    {"id": 4, "name": "xak", "faction": "Horde", "c": True, "s": True, "r": True, "is_sodam": False},
    {"id": 5, "name": "edd", "faction": "Horde", "c": True, "s": True, "r": True, "is_sodam": False},
    {"id": 6, "name": "bosse", "faction": "Horde", "c": False, "s": True, "r": False, "is_sodam": False},
    {"id": 7, "name": "bancai", "faction": "Horde", "c": True, "s": True, "r": False, "is_sodam": False},
    {"id": 8, "name": "raksodwarf", "faction": "Horde", "c": False, "s": True, "r": True, "is_sodam": False},
    {"id": 9, "name": "Erelja", "faction": "Horde", "c": False, "s": True, "r": True, "is_sodam": False},
    {"id": 10, "name": "sam", "faction": "Horde", "c": False, "s": False, "r": True, "is_sodam": False},
    {"id": 11, "name": "ayer", "faction": "Horde", "c": True, "s": True, "r": True, "is_sodam": False},
    {"id": 12, "name": "elstongnome", "faction": "Horde", "c": False, "s": True, "r": True, "is_sodam": False},
    {"id": 13, "name": "megadave", "faction": "Horde", "c": True, "s": True, "r": False, "is_sodam": False},
    {"id": 14, "name": "Maxibon", "faction": "Horde", "c": True, "s": True, "r": False, "is_sodam": False},
    {"id": 15, "name": "scam", "faction": "Horde", "c": True, "s": True, "r": True, "is_sodam": False},
    {"id": 16, "name": "wondo", "faction": "Horde", "c": True, "s": False, "r": True, "is_sodam": False},
    {"id": 17, "name": "fartlordx", "faction": "Horde", "c": True, "s": True, "r": True, "is_sodam": False},
    {"id": 18, "name": "Nexu / Deneve", "faction": "Horde", "c": True, "s": True, "r": False, "is_sodam": False},
    {"id": 19, "name": "Vanargand", "faction": "Horde", "c": True, "s": False, "r": True, "is_sodam": False},
    {"id": 22, "name": "brokest boi", "faction": "Horde", "c": True, "s": True, "r": True, "is_sodam": False},

    # Alliance (22)
    {"id": 20, "name": "sodam", "faction": "Alliance", "c": True, "s": True, "r": True, "is_sodam": True},
    {"id": 21, "name": "falkoro", "faction": "Alliance", "c": False, "s": False, "r": False, "is_sodam": False},
    {"id": 23, "name": "thistlewind", "faction": "Alliance", "c": False, "s": True, "r": True, "is_sodam": False},
    {"id": 24, "name": "neych", "faction": "Alliance", "c": False, "s": True, "r": True, "is_sodam": False},
    {"id": 25, "name": "grimzzy", "faction": "Alliance", "c": True, "s": True, "r": True, "is_sodam": False},
    {"id": 26, "name": "mcflash", "faction": "Alliance", "c": False, "s": True, "r": True, "is_sodam": False},
    {"id": 27, "name": "monarch", "faction": "Alliance", "c": True, "s": True, "r": False, "is_sodam": False},
    {"id": 28, "name": "bob", "faction": "Alliance", "c": False, "s": True, "r": True, "is_sodam": False},
    {"id": 29, "name": "Biolume", "faction": "Alliance", "c": False, "s": True, "r": False, "is_sodam": False},
    {"id": 30, "name": "purpleman", "faction": "Alliance", "c": True, "s": True, "r": True, "is_sodam": False},
    {"id": 31, "name": "yucca", "faction": "Alliance", "c": True, "s": True, "r": False, "is_sodam": False},
    {"id": 32, "name": "cloggy", "faction": "Alliance", "c": False, "s": True, "r": True, "is_sodam": False},
    {"id": 33, "name": "malc", "faction": "Alliance", "c": True, "s": True, "r": True, "is_sodam": False},
    {"id": 34, "name": "glen", "faction": "Alliance", "c": False, "s": True, "r": False, "is_sodam": False},
    {"id": 35, "name": "zerodas", "faction": "Alliance", "c": False, "s": True, "r": True, "is_sodam": False},
    {"id": 36, "name": "starfirebeam", "faction": "Alliance", "c": False, "s": True, "r": True, "is_sodam": False},
    {"id": 37, "name": "celth", "faction": "Alliance", "c": True, "s": True, "r": False, "is_sodam": False},
    {"id": 38, "name": "chobo", "faction": "Alliance", "c": False, "s": False, "r": False, "is_sodam": False},
    {"id": 39, "name": "port", "faction": "Alliance", "c": True, "s": True, "r": True, "is_sodam": False},
    {"id": 40, "name": "droggo", "faction": "Alliance", "c": True, "s": True, "r": False, "is_sodam": False},
    {"id": 41, "name": "atoz", "faction": "Alliance", "c": True, "s": False, "r": False, "is_sodam": False},
    {"id": 42, "name": "noxqs", "faction": "Alliance", "c": False, "s": True, "r": False, "is_sodam": False},
]

DEFAULT_SETTINGS = {
    "w_classic": "1",
    "w_sod": "1",
    "w_retail": "1",
    "voting_mode": "onevote",
}


GCS_BUCKET = os.environ.get("GCS_BUCKET")
_storage_client = None
gcs_sync_pending = False


def get_storage_client():
    global _storage_client
    if _storage_client is None:
        try:
            from google.cloud import storage
            _storage_client = storage.Client()
        except Exception as e:
            print(f"⚠️ Warning: Could not initialize Google Cloud Storage client: {e}")
            return None
    return _storage_client


def sync_from_gcs():
    if not GCS_BUCKET:
        return
    client = get_storage_client()
    if not client:
        return
    try:
        bucket = client.bucket(GCS_BUCKET)
        blob = bucket.blob("wow_vote.db")
        if blob.exists():
            print(f"📥 Downloading latest database from gs://{GCS_BUCKET}/wow_vote.db ...")
            blob.download_to_filename(str(DB_PATH))
            print("✅ Database successfully restored from GCS.")
        else:
            print(f"ℹ️ No database found in gs://{GCS_BUCKET}/wow_vote.db. Initial seed will be uploaded.")
    except Exception as e:
        print(f"⚠️ Warning: Failed to sync database from GCS: {e}")


def sync_to_gcs():
    global gcs_sync_pending
    if not GCS_BUCKET:
        return True
    gcs_sync_pending = True
    client = get_storage_client()
    if not client:
        return False
    try:
        # Checkpoint WAL so that all data is flushed from WAL into the main DB file
        conn = sqlite3.connect(DB_PATH)
        conn.execute("PRAGMA wal_checkpoint(TRUNCATE)")
        conn.close()

        bucket = client.bucket(GCS_BUCKET)
        blob = bucket.blob("wow_vote.db")
        blob.upload_from_filename(str(DB_PATH))
        gcs_sync_pending = False
        print(f"📤 Database successfully synced to gs://{GCS_BUCKET}/wow_vote.db")
        return True
    except Exception as e:
        print(f"⚠️ Warning: Failed to sync database to GCS: {e}")
        return False


def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    return conn


def init_db():
    sync_from_gcs()
    conn = get_db()
    seeded = False
    with conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS players (
                id INTEGER PRIMARY KEY,
                name TEXT NOT NULL,
                faction TEXT NOT NULL,
                classic INTEGER NOT NULL DEFAULT 0,
                sod INTEGER NOT NULL DEFAULT 0,
                retail INTEGER NOT NULL DEFAULT 0,
                is_sodam INTEGER NOT NULL DEFAULT 0
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS settings (
                key TEXT PRIMARY KEY,
                value TEXT NOT NULL
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS vote_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                player_id INTEGER,
                player_name TEXT NOT NULL,
                old_faction TEXT,
                new_faction TEXT NOT NULL,
                changed_by TEXT NOT NULL DEFAULT 'admin',
                timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                details TEXT
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS discord_voters (
                user_id TEXT PRIMARY KEY,
                player_id INTEGER,
                display_name TEXT NOT NULL,
                faction TEXT NOT NULL
            )
        """)

        # Check if players table is empty, seed if so
        cur = conn.execute("SELECT COUNT(*) as count FROM players")
        if cur.fetchone()["count"] == 0:
            seeded = True
            for p in DEFAULT_PLAYERS:
                conn.execute(
                    """
                    INSERT INTO players (id, name, faction, classic, sod, retail, is_sodam)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        p["id"],
                        p["name"],
                        p["faction"],
                        1 if p["c"] else 0,
                        1 if p["s"] else 0,
                        1 if p["r"] else 0,
                        1 if p["is_sodam"] else 0,
                    ),
                )

        # Check if settings are seeded
        for k, v in DEFAULT_SETTINGS.items():
            conn.execute(
                "INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)", (k, v)
            )

    if seeded:
        sync_to_gcs()
    conn.close()


init_db()


class PlayerUpdate(BaseModel):
    name: Optional[str] = None
    faction: Optional[str] = None
    c: Optional[bool] = None
    s: Optional[bool] = None
    r: Optional[bool] = None


class PlayerCreate(BaseModel):
    name: str
    faction: str = "Alliance"
    c: bool = False
    s: bool = False
    r: bool = False


class SettingsUpdate(BaseModel):
    w_classic: Optional[float] = None
    w_sod: Optional[float] = None
    w_retail: Optional[float] = None
    voting_mode: Optional[str] = None


@app.get("/", response_class=HTMLResponse)
@app.get("/admin", response_class=HTMLResponse)
@app.get("/manage", response_class=HTMLResponse)
def serve_home():
    if not HTML_PATH.exists():
        raise HTTPException(status_code=404, detail="index.html not found")
    html = HTML_PATH.read_text(encoding="utf-8")
    return html.replace(MAP_PLACEHOLDER, MAP_PATH.read_text(encoding="utf-8"), 1)


@app.get("/history", response_class=HTMLResponse)
def serve_history():
    if not HISTORY_PATH.exists():
        raise HTTPException(status_code=404, detail="history.html not found")
    return HISTORY_PATH.read_text(encoding="utf-8")


@app.get("/favicon.ico", include_in_schema=False)
def serve_favicon():
    return FileResponse(STATIC_DIR / "favicon.ico", media_type="image/x-icon")


@app.get("/api/state")
def get_state():
    conn = get_db()
    with conn:
        p_rows = conn.execute("SELECT * FROM players ORDER BY id ASC").fetchall()
        s_rows = conn.execute("SELECT key, value FROM settings").fetchall()
    conn.close()

    players = [
        {
            "id": r["id"],
            "name": r["name"],
            "faction": r["faction"],
            "c": bool(r["classic"]),
            "s": bool(r["sod"]),
            "r": bool(r["retail"]),
            "isSodam": bool(r["is_sodam"]),
        }
        for r in p_rows
    ]

    settings = {r["key"]: r["value"] for r in s_rows}
    settings_out = {
        "w_classic": float(settings.get("w_classic", 1)),
        "w_sod": float(settings.get("w_sod", 1)),
        "w_retail": float(settings.get("w_retail", 1)),
        "voting_mode": settings.get("voting_mode", "onevote"),
    }

    return {"players": players, "settings": settings_out}


@app.post("/api/players")
def create_player(player: PlayerCreate):
    name = player.name.strip()
    if not name:
        raise HTTPException(status_code=400, detail="Name cannot be empty")
    if player.faction not in ("Horde", "Alliance", "Abstain"):
        raise HTTPException(status_code=400, detail="Invalid faction")

    conn = get_db()
    with conn:
        cur = conn.execute(
            """
            INSERT INTO players (name, faction, classic, sod, retail, is_sodam)
            VALUES (?, ?, ?, ?, ?, 0)
            """,
            (
                name,
                player.faction,
                1 if player.c else 0,
                1 if player.s else 0,
                1 if player.r else 0,
            ),
        )
        new_id = cur.lastrowid
        row = conn.execute("SELECT * FROM players WHERE id = ?", (new_id,)).fetchone()
        conn.execute(
            """
            INSERT INTO vote_history (player_id, player_name, old_faction, new_faction, changed_by, details)
            VALUES (?, ?, ?, ?, 'admin', 'Added new member to roster')
            """,
            (new_id, name, None, player.faction),
        )

    sync_to_gcs()

    return {
        "id": row["id"],
        "name": row["name"],
        "faction": row["faction"],
        "c": bool(row["classic"]),
        "s": bool(row["sod"]),
        "r": bool(row["retail"]),
        "isSodam": bool(row["is_sodam"]),
    }


@app.delete("/api/players/{player_id}")
def delete_player(player_id: int):
    conn = get_db()
    with conn:
        row = conn.execute("SELECT * FROM players WHERE id = ?", (player_id,)).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Player not found")

        conn.execute(
            """
            INSERT INTO vote_history (player_id, player_name, old_faction, new_faction, changed_by, details)
            VALUES (?, ?, ?, 'Removed', 'admin', 'Removed member from roster')
            """,
            (player_id, row["name"], row["faction"]),
        )
        conn.execute("DELETE FROM players WHERE id = ?", (player_id,))

    sync_to_gcs()
    return {"status": "deleted", "id": player_id}


@app.patch("/api/players/{player_id}")
def update_player(player_id: int, update: PlayerUpdate):
    conn = get_db()
    with conn:
        cur = conn.execute("SELECT * FROM players WHERE id = ?", (player_id,))
        row = cur.fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Player not found")

        updates = []
        params = []
        if update.name is not None:
            clean_name = update.name.strip()
            if not clean_name:
                raise HTTPException(status_code=400, detail="Name cannot be empty")
            updates.append("name = ?")
            params.append(clean_name)

        if update.faction is not None:
            if update.faction not in ("Horde", "Alliance", "Abstain"):
                raise HTTPException(status_code=400, detail="Invalid faction")
            if update.faction != row["faction"]:
                conn.execute(
                    """
                    INSERT INTO vote_history (player_id, player_name, old_faction, new_faction, changed_by, details)
                    VALUES (?, ?, ?, ?, 'admin', 'Manual change in Admin panel')
                    """,
                    (player_id, row["name"], row["faction"], update.faction),
                )
            updates.append("faction = ?")
            params.append(update.faction)

        if update.c is not None:
            updates.append("classic = ?")
            params.append(1 if update.c else 0)

        if update.s is not None:
            updates.append("sod = ?")
            params.append(1 if update.s else 0)

        if update.r is not None:
            updates.append("retail = ?")
            params.append(1 if update.r else 0)

        if updates:
            params.append(player_id)
            query = f"UPDATE players SET {', '.join(updates)} WHERE id = ?"
            conn.execute(query, tuple(params))

        updated_row = conn.execute("SELECT * FROM players WHERE id = ?", (player_id,)).fetchone()

    sync_to_gcs()

    return {
        "id": updated_row["id"],
        "name": updated_row["name"],
        "faction": updated_row["faction"],
        "c": bool(updated_row["classic"]),
        "s": bool(updated_row["sod"]),
        "r": bool(updated_row["retail"]),
        "isSodam": bool(updated_row["is_sodam"]),
    }


@app.patch("/api/settings")
def update_settings(update: SettingsUpdate):
    conn = get_db()
    with conn:
        if update.w_classic is not None:
            conn.execute("INSERT OR REPLACE INTO settings (key, value) VALUES ('w_classic', ?)", (str(update.w_classic),))
        if update.w_sod is not None:
            conn.execute("INSERT OR REPLACE INTO settings (key, value) VALUES ('w_sod', ?)", (str(update.w_sod),))
        if update.w_retail is not None:
            conn.execute("INSERT OR REPLACE INTO settings (key, value) VALUES ('w_retail', ?)", (str(update.w_retail),))
        if update.voting_mode is not None:
            if update.voting_mode not in ("weighted", "onevote"):
                raise HTTPException(status_code=400, detail="Invalid voting mode")
            conn.execute("INSERT OR REPLACE INTO settings (key, value) VALUES ('voting_mode', ?)", (update.voting_mode,))

    sync_to_gcs()

    return {"status": "ok"}


@app.post("/api/reset")
def reset_database():
    raise HTTPException(status_code=403, detail="Reset roster has been permanently disabled.")


DISCORD_BOT_TOKEN = os.environ.get("DISCORD_BOT_TOKEN", "")
DISCORD_API = "https://discord.com/api/v10"
DEFAULT_GUILD_ID = os.environ.get("DISCORD_GUILD_ID", "1172965723467956365")
DEFAULT_CHANNEL_ID = os.environ.get("DISCORD_CHANNEL_ID", "1548578917965635675")
DEFAULT_MESSAGE_ID = os.environ.get("DISCORD_MESSAGE_ID", "1548585777326329887")


def normalize_name(s: str) -> str:
    if not s:
        return ""
    import unicodedata
    s = unicodedata.normalize("NFKD", s).encode("ASCII", "ignore").decode("utf-8")
    return s.lower().replace(" ", "").replace("_", "").replace(".", "").replace("/", "").strip()


def _sync_discord_votes():
    bot_token = os.environ.get("DISCORD_BOT_TOKEN", DISCORD_BOT_TOKEN)
    if not bot_token:
        raise HTTPException(status_code=500, detail="DISCORD_BOT_TOKEN environment variable not set")

    c_id = DEFAULT_CHANNEL_ID
    m_id = DEFAULT_MESSAGE_ID
    g_id = DEFAULT_GUILD_ID

    headers = {
        "Authorization": f"Bot {bot_token}",
        "User-Agent": "WoWFactionVoteBot (https://wow-faction-vote, 1.0)",
    }

    def discord_fetch(endpoint: str, allow_missing: bool = False):
        url = f"{DISCORD_API}{endpoint}"
        req = urllib.request.Request(url, headers=headers)
        for attempt in range(4):
            try:
                with urllib.request.urlopen(req, timeout=15) as resp:
                    return json.loads(resp.read().decode("utf-8"))
            except urllib.error.HTTPError as e:
                if allow_missing and e.code == 404:
                    return {}
                if e.code == 429:
                    try:
                        delay = float(e.headers.get("Retry-After", "60"))
                    except (TypeError, ValueError):
                        delay = 60
                    if attempt < 3 and 0 <= delay <= 30:
                        time.sleep(delay + 0.25)
                        continue
                    raise HTTPException(status_code=429, detail="Discord API rate limited") from e
                # A failed fetch must never be mistaken for an empty poll.
                raise HTTPException(status_code=502, detail=f"Discord API returned {e.code}") from e
            except (urllib.error.URLError, TimeoutError, ValueError) as e:
                raise HTTPException(status_code=502, detail="Discord API unavailable") from e

    def answer_voters(answer_id: int):
        users = []
        after = None
        while True:
            endpoint = f"/channels/{c_id}/polls/{m_id}/answers/{answer_id}?limit=100"
            if after:
                endpoint += f"&after={after}"
            page = discord_fetch(endpoint)
            batch = page.get("users")
            if not isinstance(batch, list):
                raise HTTPException(status_code=502, detail="Invalid Discord poll response")
            users.extend(batch)
            if len(batch) < 100:
                return users
            after = batch[-1]["id"]

    # Fetch users from Discord Native Poll: Answer 1 = Horde, Answer 2 = Alliance
    horde_users = answer_voters(1)
    ally_users = answer_voters(2)

    user_votes = {}
    for u in ally_users:
        uid = u["id"]
        if uid not in user_votes:
            user_votes[uid] = {"voted_ally": False, "voted_horde": False, "u": u}
        user_votes[uid]["voted_ally"] = True

    for u in horde_users:
        uid = u["id"]
        if uid not in user_votes:
            user_votes[uid] = {"voted_ally": False, "voted_horde": False, "u": u}
        user_votes[uid]["voted_horde"] = True

    conn = get_db()
    updated = []
    unmatched = []
    changed = False

    with conn:
        all_players = conn.execute("SELECT id, name, faction FROM players").fetchall()
        players_by_id = {p["id"]: p for p in all_players}
        known_voters = {
            row["user_id"]: row
            for row in conn.execute("SELECT * FROM discord_voters").fetchall()
        }
        current_factions = {p["id"]: p["faction"] for p in all_players}

        for uid, d in user_votes.items():
            u = d["u"]
            known = known_voters.get(uid)
            uname = u.get("username")
            gname = u.get("global_name")

            if d["voted_ally"] and d["voted_horde"]:
                vote_faction = "Abstain"  # Contested / Both
            elif d["voted_ally"]:
                vote_faction = "Alliance"
            elif d["voted_horde"]:
                vote_faction = "Horde"
            else:
                continue

            matched_player = players_by_id.get(known["player_id"]) if known else None
            display_name = (known["display_name"] if known else None) or gname or uname or uid
            if not matched_player:
                m_info = discord_fetch(f"/guilds/{g_id}/members/{uid}", allow_missing=True) if not known else {}
                nick = m_info.get("nick") if m_info else None
                display_name = nick or gname or uname or uid
                if known:
                    display_name = known["display_name"]
                candidates = [c for c in [nick, known["display_name"] if known else None, gname, uname] if c]
                for p in all_players:
                    norm_p = normalize_name(p["name"])
                    for c in candidates:
                        norm_c = normalize_name(c)
                        if norm_p == norm_c or norm_p in norm_c or norm_c in norm_p:
                            matched_player = p
                            break
                        # Special guild aliases
                        if ("xak" in norm_p and "agravain" in norm_c) or ("agravain" in norm_p and "xak" in norm_c):
                            matched_player = p
                            break
                        if ("fartlord" in norm_p and "tom" in norm_c) or ("tom" in norm_p and "fartlord" in norm_c):
                            matched_player = p
                            break
                        if ("purpleman" in norm_p and "marsian" in norm_c) or ("marsian" in norm_p and "purpleman" in norm_c):
                            matched_player = p
                            break
                        if ("brokest" in norm_p and "slavedemorto" in norm_c) or ("slavedemorto" in norm_p and "brokest" in norm_c):
                            matched_player = p
                            break
                        if ("erelja" in norm_p and "erellja" in norm_c) or ("erellja" in norm_p and "erelja" in norm_c):
                            matched_player = p
                            break
                    if matched_player:
                        break

            player_id = matched_player["id"] if matched_player else None
            if not known or known["player_id"] != player_id or known["faction"] != vote_faction:
                conn.execute(
                    "INSERT OR REPLACE INTO discord_voters (user_id, player_id, display_name, faction) VALUES (?, ?, ?, ?)",
                    (uid, player_id, display_name, vote_faction),
                )
                changed = True

            if matched_player:
                old_f = current_factions[player_id]
                if vote_faction != old_f:
                    conn.execute(
                        """
                        INSERT INTO vote_history (player_id, player_name, old_faction, new_faction, changed_by, details)
                        VALUES (?, ?, ?, ?, 'discord_sync', ?)
                        """,
                        (player_id, matched_player["name"], old_f, vote_faction, f"Discord poll vote ({display_name})"),
                    )
                    conn.execute("UPDATE players SET faction = ? WHERE id = ?", (vote_faction, player_id))
                    current_factions[player_id] = vote_faction
                    changed = True
                updated.append({
                    "id": player_id,
                    "name": matched_player["name"],
                    "old_faction": old_f,
                    "new_faction": vote_faction,
                    "discord_nick": display_name,
                })
            else:
                unmatched.append({
                    "discord_id": uid,
                    "name": display_name,
                    "faction": vote_faction,
                })

        # A previously observed voter who disappears from both answers withdrew their vote.
        for uid, known in known_voters.items():
            if uid in user_votes or known["faction"] == "Abstain":
                continue
            conn.execute("UPDATE discord_voters SET faction = 'Abstain' WHERE user_id = ?", (uid,))
            changed = True
            player = players_by_id.get(known["player_id"])
            if player and current_factions[player["id"]] != "Abstain":
                old_f = current_factions[player["id"]]
                conn.execute(
                    "INSERT INTO vote_history (player_id, player_name, old_faction, new_faction, changed_by, details) VALUES (?, ?, ?, 'Abstain', 'discord_sync', ?)",
                    (player["id"], player["name"], old_f, f"Discord poll vote removed ({known['display_name']})"),
                )
                conn.execute("UPDATE players SET faction = 'Abstain' WHERE id = ?", (player["id"],))
                current_factions[player["id"]] = "Abstain"

    conn.close()
    if (changed or gcs_sync_pending) and not sync_to_gcs():
        raise HTTPException(status_code=503, detail="Database backup to GCS failed")

    return {
        "status": "ok",
        "synced_count": len(updated),
        "changed": changed,
        "updated": updated,
        "unmatched": unmatched,
        "horde_poll_votes": len(horde_users),
        "alliance_poll_votes": len(ally_users),
    }


@app.post("/api/discord/sync")
def sync_discord_votes(request: Request):
    expected = os.environ.get("SYNC_TOKEN", "")
    supplied = request.headers.get("X-Sync-Token", "")
    if not expected:
        raise HTTPException(status_code=503, detail="SYNC_TOKEN is not configured")
    if not hmac.compare_digest(supplied, expected):
        raise HTTPException(status_code=401, detail="Invalid sync token")
    if not sync_lock.acquire(blocking=False):
        raise HTTPException(status_code=409, detail="Sync already in progress")
    try:
        return _sync_discord_votes()
    finally:
        sync_lock.release()


@app.get("/api/history")
def get_vote_history(limit: int = 200):
    conn = get_db()
    rows = conn.execute(
        "SELECT id, player_id, player_name, old_faction, new_faction, changed_by, timestamp, details FROM vote_history ORDER BY id DESC LIMIT ?",
        (limit,)
    ).fetchall()
    conn.close()
    return [
        {
            "id": r["id"],
            "player_id": r["player_id"],
            "player_name": r["player_name"],
            "old_faction": r["old_faction"],
            "new_faction": r["new_faction"],
            "changed_by": r["changed_by"],
            "timestamp": r["timestamp"],
            "details": r["details"],
        }
        for r in rows
    ]


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8000))
    host = os.environ.get("HOST", "127.0.0.1")
    print("🚀 Starting WoW Forever Faction Vote Server...")
    print(f"👉 Open your browser at: http://{host}:{port}")
    uvicorn.run("server:app", host=host, port=port, reload=(host == "127.0.0.1"))

